### ISSUE TITLE
Move template and styles out of esri4-map.component.ts

### ISSUE THREAD

**Issue by TheKeithStewart** [TheKeithStewart/angular2-esri4-components#1]
Had to move them to be inline because of errors when referencing these paths.

**Comment by kgs916** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #1: Move template and styles out of esri4-map.component.ts](https://trello.com/c/qlN5S4JC/2-issue-1-move-template-and-styles-out-of-esri4-map-component-ts)

**Comment by TheKeithStewart** [comment]
It is recommended to keep templates and styles inline in component libraries in the library spec published by Google at https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview.
