### ISSUE TITLE
Feature Layer

### ISSUE THREAD

**Issue by derobiom** [TheKeithStewart/angular2-esri4-components#12]
### How might I translate the code below (from an esri example) to use this module?  I have feature layers on my ArcGIS server that I want to show & query.  I have tried using "new __esri.FeatureLayer(..." but at run time I get a "__esri is not defined" error.  And we don't currently use portal.
===========================================
require(["esri/layers/FeatureLayer"], function(FeatureLayer){
  // points to the states layer in a service storing U.S. census data
  var fl = new FeatureLayer({
    url: "https://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3"
  });
  map.add(fl);  // adds the layer to the map
});

**Comment by TheKeithStewart** [comment]
@derobiom 

`__esri` is simply a namespace used by TypeScript to give you access to the type definitions for ESRI.  It is not an object that exists in your compiled JavaScript and therefor can't be used that way you are describing.

You can use the `EsriLoaderService` To import the FeatureLayer module.  Below is an example of what a component might look like that does what you are describing:

```
import { Component } from '@angular/core';

import { Esri4MapComponent } from 'angular2-esri4-components';
import { EsriLoaderService } from 'angular2-esri-loader';

@Component({
  selector: 'app-map',
  template: `
    <esri4-map [mapProperties]="mapProperties" [mapViewProperties]="mapViewProperties" (mapInit)="onMapInit($event)"></esri4-map>
  `,
  styleUrls: ['./map.component.scss']
})
export class MapComponent {
  /* ... */
  constructor(private esriLoader: EsriLoaderService) { }

  onMapInit(mapInfo: { map: __esri.Map, mapView: __esri.MapView }) {
    let map = mapInfo.map;
    let mapView = mapInfo.mapView;

    this.esriLoader.loadModules([
      'esri/layers/FeatureLayer'
    ]).then(([FeatureLayer]: [__esri.FeatureLayerConstructor]) => {
      const fl = new FeatureLayer({
        url: "https://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3"
      });

      map.add(fl);
    });
  }
}
```
